version: "2"

services:
  hass:
    image: djdefi/rpi-homeassistant
    ports:
      - 8123:8123
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
      - VIRTUAL_HOST=defiha.duckdns.org
      - LETSENCRYPT_HOST=defiha.duckdns.org
      - LETSENCRYPT_EMAIL=djdefi@gmail.com
networks:
  default:
    external:
      name: nginx-proxy    
