version: "2"

services:
  hass:
    build: .
    ports:
      - 8123:8123
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    environment:
      - TZ=America/Los_Angeles
